#.
# If set to true blocks will not be breakable if they do not have a tier assigned.
#If set to false blocks will be breakable by anything if they dont have a tier assigned.
#
# Default: true
"Force Tier" = true
#.
# If set to true tools need to be above the tier of the block, or match exactly.
#If set to false tools need to be above or at the same tier of the block.
#
# Default: true
"Equal Tier" = true
#.
# If set to true, all blocks that have a tool assigned to them but no tier will automatically be assigned to the wooden tier
#
# Default: true
"Lenient Matching" = true
#.
# If a block is missing the "requiresCorrectToolForDrops" property and this is set to false, they will get assigned to the Hand tier.
#If set to true we force the tier and ignore the missing requirement.
#
# Default: true
"Tool Overwrite" = true
